-- CreateTable
CREATE TABLE "Todo" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "title" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "complete" BOOLEAN NOT NULL DEFAULT false,
    "goal" REAL NOT NULL DEFAULT 1.0,
    "hoursWeek" REAL NOT NULL DEFAULT 0,
    "hoursDay" REAL NOT NULL DEFAULT 0,
    "hoursMonth" REAL NOT NULL DEFAULT 0
);
